import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, Mail, MessageCircle, Linkedin, Instagram, Github } from "lucide-react";
import { Navigation } from "./navigation";
import { Analytics } from "./analytics";
import type { SiteSettings, ContentRecord } from "@/types/content";
import { safeUrl } from "@/lib/utils";
export function ProjectCTA() { return <section className="container cta-section"><div><span className="eyebrow light">THE NEXT CHAPTER STARTS HERE</span><h2>Have a project in mind?<br /><span>Let’s make it happen.</span></h2></div><div><Link href="/contact" className="button white">Start a conversation <ArrowUpRight size={18}/></Link><p>Good things start with a simple hello.</p></div><div className="cta-symbol" aria-hidden="true">↗</div></section>; }
export function PublicShell({ children, settings, services }: {
    children: React.ReactNode;
    settings: SiteSettings;
    services: ContentRecord[];
}) { const whatsapp = `https://wa.me/${settings.whatsapp}?text=${encodeURIComponent("Halo KodeaTech, saya ingin berkonsultasi mengenai kebutuhan IT.")}`; return <><a className="skip-link" href="#main">Skip to content</a><Navigation companyName={settings.companyName} logo={settings.logo}/><main id="main">{children}</main><ProjectCTA /><footer className="site-footer container"><div className="footer-grid"><div><Link href="/" className="brand" aria-label={`${settings.companyName} home`}>{settings.logo ? <Image src={settings.logo} alt={settings.companyName} width={150} height={40}/> : <><span className="brand-mark">k<span>↗</span></span>{settings.companyName}</>}</Link><p>{settings.tagline}</p><a className="footer-email" href={`mailto:${settings.email}`}><Mail size={15}/>{settings.email}</a><div className="social-links">{[[settings.linkedin, Linkedin, "LinkedIn"], [settings.instagram, Instagram, "Instagram"], [settings.github, Github, "GitHub"]].map(([url, Icon, label]) => typeof url === "string" && url && typeof Icon !== "string" && <a key={String(label)} href={safeUrl(url)} aria-label={String(label)} target="_blank" rel="noopener noreferrer"><Icon size={17}/></a>)}</div></div><div><h3>What we do</h3>{services.slice(0, 5).map(s => <Link key={s.id} href={`/services/${s.slug}`}>{s.title.replace(" Development", "")}</Link>)}</div><div><h3>Company</h3>{[["About us", "about"], ["Our work", "portfolio"], ["Partners", "partners"], ["Careers", "careers"]].map(([n, s]) => <Link key={s} href={`/${s}`}>{n}</Link>)}</div><div><h3>Let’s connect</h3><Link href="/contact">Start a project</Link><Link href="/solutions">Our solutions</Link><Link href="/blog">Insights & ideas</Link><a href={whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp us <ArrowUpRight size={12}/></a><small>{settings.address}</small></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {settings.copyright}</span><div><Link href="/privacy-policy">Privacy policy</Link><Link href="/terms">Terms & conditions</Link></div><span className="footer-note"><span className="status-dot"/> {settings.supportLabel}</span></div></footer><a className="whatsapp" href={whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Chat with us on WhatsApp"><MessageCircle size={22}/><span>Chat with us</span></a><Analytics id={process.env.GOOGLE_ANALYTICS_ID || settings.gaId}/></>; }
