"use client";
import { useCallback, useState } from "react";
import { ImageField } from "./image-picker";
import { Save, Plus, Trash2 } from "lucide-react";
import type { SiteSettings } from "@/types/content";
import { useAdmin } from "@/hooks/use-admin";
import { Notice } from "./notice";
const groups: {
    title: string;
    description: string;
    fields: [
        keyof SiteSettings,
        string,
        string?
    ][];
}[] = [{ title: "Brand & company", description: "Your identity, everywhere on the website.", fields: [["companyName", "Company name"], ["tagline", "Tagline"], ["logo", "Company logo", "image"], ["favicon", "Favicon", "image"], ["copyright", "Copyright text"], ["supportLabel", "Footer status label"]] }, { title: "Contact & social", description: "Replace the example WhatsApp number before going live.", fields: [["email", "Email", "email"], ["phone", "Phone"], ["whatsapp", "WhatsApp number (digits only)"], ["address", "Address", "textarea"], ["mapsUrl", "Google Maps embed URL"], ["linkedin", "LinkedIn"], ["instagram", "Instagram"], ["github", "GitHub"]] }, { title: "Homepage hero", description: "The first impression, in your words.", fields: [["heroImage", "Homepage hero image (optional)", "image"], ["heroLabel", "Eyebrow"], ["heroTitle", "Headline"], ["heroAccent", "Highlighted headline"], ["heroSubtitle", "Supporting copy", "textarea"], ["ctaLabel", "Primary CTA label"], ["ctaUrl", "Primary CTA URL"], ["secondaryCtaLabel", "Secondary CTA label"], ["secondaryCtaUrl", "Secondary CTA URL"]] }, { title: "About & technology", description: "Featured content is selected from the relevant content lists.", fields: [["aboutImage", "Homepage about image (optional)", "image"], ["aboutTitle", "About heading"], ["aboutText", "About copy", "textarea"], ["technologiesIntro", "Technology section description", "textarea"]] }, { title: "Global SEO & analytics", description: "Analytics is enabled only after visitor consent. Environment variables override tracking settings.", fields: [["seoTitle", "Default SEO title"], ["seoDescription", "Default meta description", "textarea"], ["ogImage", "Default Open Graph image", "image"], ["gaId", "Google Analytics measurement ID"], ["searchVerification", "Google Search Console verification token"]] }];
export function SettingsEditor({ settings, csrf }: {
    settings: SiteSettings;
    csrf: string;
}) { const [uploads, setUploads] = useState(0); const uploadActivity = useCallback((active: boolean) => setUploads(n => Math.max(0, n + (active ? 1 : -1))), []); const [data, setData] = useState(settings), [tab, setTab] = useState(0), { request, busy, notice } = useAdmin(csrf); return <form onSubmit={e => { e.preventDefault(); if (uploads || busy) return; request("/api/admin/settings", data); }}><div className="admin-page-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h1>Website settings</h1><p>Manage your brand, homepage, contact details, and integrations.</p></div><button className="button" disabled={busy || uploads > 0}><Save size={17}/>{uploads ? "Uploading…" : busy ? "Saving…" : "Save settings"}</button></div><div className="settings-layout"><nav className="settings-nav" aria-label="Settings categories">{groups.map((g, i) => <button type="button" disabled={uploads > 0} key={g.title} className={tab === i ? "active" : ""} onClick={() => setTab(i)}>{g.title}</button>)}<button type="button" disabled={uploads > 0} className={tab === 5 ? "active" : ""} onClick={() => setTab(5)}>Homepage statistics</button></nav><section className="admin-panel settings-fields">{tab < 5 ? <><h2>{groups[tab].title}</h2><p>{groups[tab].description}</p>{groups[tab].fields.map(([key, label, type]) => type === "image" ? <ImageField key={key} label={label} value={String(data[key] || "")} csrf={csrf} onUploadActivity={uploadActivity} onChange={urls => setData(d => ({ ...d, [key]: urls[0] || "" }))}/> : <label key={key}>{label}{type === "textarea" ? <textarea rows={4} value={String(data[key])} onChange={e => setData(d => ({ ...d, [key]: e.target.value }))}/> : <input type={type || "text"} value={String(data[key])} onChange={e => setData(d => ({ ...d, [key]: e.target.value }))}/>}</label>)}</> : <><h2>Homepage statistics</h2><p>Publish only figures you can substantiate. Labels and values are fully editable.</p>{data.stats.map((s, i) => <div className="stat-editor" key={i}><label>Value<input value={s.value} onChange={e => setData(d => ({ ...d, stats: d.stats.map((v, j) => j === i ? { ...v, value: e.target.value } : v) }))}/></label><label>Label<input value={s.label} onChange={e => setData(d => ({ ...d, stats: d.stats.map((v, j) => j === i ? { ...v, label: e.target.value } : v) }))}/></label><button type="button" className="icon-button" aria-label="Remove statistic" onClick={() => setData(d => ({ ...d, stats: d.stats.filter((_, j) => j !== i) }))}><Trash2 size={17}/></button></div>)}{data.stats.length < 8 && <button type="button" className="button secondary" onClick={() => setData(d => ({ ...d, stats: [...d.stats, { value: "0", label: "New statistic" }] }))}><Plus size={16}/>Add statistic</button>}</>}</section></div><Notice notice={notice}/></form>; }
