import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, ArrowRight, Check } from "lucide-react";
import { getSettings } from "@/services/settings";
import { listContent } from "@/services/content";
import { pageMetadata } from "@/services/seo";
import { NetworkVisual } from "@/components/network-visual";
import { Reveal, Stat } from "@/components/motion";
import { ServiceCard, ProjectCard, BlogCard } from "@/components/content-cards";
import { Testimonials } from "@/components/testimonial-slider";
import { ClientLogoWall } from "@/components/client-logo-wall";
import { ServiceIcon } from "@/components/icons";
import { obj, stringValue, safeUrl } from "@/lib/utils";
export async function generateMetadata() { return pageMetadata("/"); }
export default async function Home() {
    const [s, services, solutions, projects, testimonials, partners, tech, posts] = await Promise.all([getSettings(), listContent("services", true), listContent("solutions", true), listContent("portfolio", true), listContent("testimonials", true), listContent("partners", true), listContent("technologies", true), listContent("blog", true)]);
    return <>
    <section className="hero container"><div className="hero-copy"><Reveal><span className="eyebrow"><span className="blue-square"/>{s.heroLabel}</span><h1>{s.heroTitle}<br /><span>{s.heroAccent}</span></h1><p>{s.heroSubtitle}</p><div className="hero-buttons"><Link href={safeUrl(s.ctaUrl)} className="button">{s.ctaLabel}<ArrowUpRight size={18}/></Link><Link href={safeUrl(s.secondaryCtaUrl)} className="text-button">{s.secondaryCtaLabel}<ArrowRight size={17}/></Link></div><div className="hero-note"><div className="mini-avatars"><span>K</span><span><CodeIcon /></span><span><Check size={12}/></span></div><span>Thoughtful engineering.<br /><strong>Lasting business impact.</strong></span></div></Reveal></div><Reveal className="hero-visual">{s.heroImage ? <Image className="homepage-hero-image" src={s.heroImage} alt={`${s.companyName} — technology that moves business forward`} width={1000} height={1000} sizes="(max-width: 768px) 100vw, 50vw" priority/> : <NetworkVisual />}</Reveal><div className="hero-foot"><span>SOFTWARE. INFRASTRUCTURE. POSSIBILITIES.</span><a href="#expertise">Discover Kodea <span>↓</span></a></div></section>
    {partners.length > 0 && <section className="trust-section container"><div className="trust-heading"><p>Didesain khusus untuk mempercepat langkah bisnis masa depan<br /><strong>dan bisnis yang siap tumbuh pesat.</strong></p><small>{partners.some(p => obj(p.data).demo === "true") ? "CLIENT WALL" : "TRUSTED BY TEAMS AND BUSINESSES"}</small></div><ClientLogoWall items={partners.map(({ id, title, image }) => ({ id, title, image }))}/></section>}
    <section id="expertise" className="section container"><Reveal className="section-heading"><div><span className="eyebrow">01 — WHAT WE DO</span><h2>A strong idea deserves<br /><span>the right expertise.</span></h2></div><div><p>Everything you need to build, connect, and grow.<br />One technology partner to bring it together.</p><Link href="/services" className="text-button">Explore all services<ArrowUpRight size={17}/></Link></div></Reveal><Reveal className="services-grid">{services.filter(x => x.featured).slice(0, 6).map((item, index) => <ServiceCard item={item} index={index} key={item.id}/>)}</Reveal><Link href="/services" className="service-bottom-link">And the infrastructure, integration, and support behind it all.<ArrowRight size={18}/></Link></section>
    <section className="about-section"><div className="container"><Reveal className="about-grid"><div><span className="eyebrow">02 — BUILT ON UNDERSTANDING</span><h2>{s.aboutTitle}</h2><Link href="/about" className="text-button">Meet KodeaTech <ArrowUpRight size={17}/></Link></div><div><p className="large-copy">{s.aboutText}</p><div className="about-principles"><span><Check size={16}/> Business-first thinking</span><span><Check size={16}/> Built for the long run</span><span><Check size={16}/> A partner, from day one</span></div></div></Reveal>{s.aboutImage && <Image className="homepage-about-image" src={s.aboutImage} alt={s.aboutTitle} width={1400} height={650} sizes="100vw"/>}<div className="stats-grid">{s.stats.map(stat => <Stat key={stat.label} {...stat}/>)}</div></div></section>
    <section className="section container"><Reveal className="section-heading"><div><span className="eyebrow">03 — SELECTED WORK</span><h2>From possibility<br /><span>to something real.</span></h2></div><div><p>A closer look at the systems we build<br />and the challenges they are designed to solve.</p><Link href="/portfolio" className="text-button">View all work <ArrowUpRight size={17}/></Link></div></Reveal><Reveal className="projects-grid">{projects.filter(p => p.featured).slice(0, 2).map(item => <ProjectCard item={item} key={item.id}/>)}</Reveal></section>
    <section className="solutions-section"><div className="container solutions-layout"><Reveal><span className="eyebrow">04 — CONNECT THE DOTS</span><h2>Different challenges.<br /><span>Connected solutions.</span></h2><p>Your technology should work together.<br />We make sure it does.</p><Link href="/solutions" className="button secondary">Discover our solutions<ArrowUpRight size={17}/></Link><div className="solution-orbit" aria-hidden="true"><div><span>k↗</span></div><i /><i /><i /></div></Reveal><Reveal className="solutions-list">{solutions.slice(0, 5).map((item, i) => <Link href={`/solutions/${item.slug}`} key={item.id}><span className="solution-number">0{i + 1}</span><span><strong>{item.title}</strong><small>{item.excerpt}</small></span><ArrowUpRight size={20}/></Link>)}</Reveal></div></section>
    <section className="section container technology-section"><Reveal><div className="center-heading"><span className="eyebrow">THE TOOLKIT BEHIND THE POSSIBILITIES</span><h2>Built with modern technology.</h2><p>{s.technologiesIntro}</p></div><div className="tech-wall">{tech.map(t => <div key={t.id}>{t.image ? <Image className="technology-logo" src={t.image} alt={`${t.title} logo`} width={36} height={36}/> : <span className="tech-symbol">{stringValue(obj(t.data).symbol)}</span>}<strong>{t.title}</strong></div>)}</div></Reveal></section>
    <section className="section container testimonial-section"><Reveal className="section-heading"><div><span className="eyebrow">GOOD WORK. GREAT PARTNERSHIPS.</span><h2>What our clients say.</h2></div><Link href="/testimonials" className="text-button">Client perspectives<ArrowUpRight size={17}/></Link></Reveal><Reveal><Testimonials items={testimonials.filter(t => t.featured)}/></Reveal></section>
    <section className="section container"><Reveal className="section-heading"><div><span className="eyebrow">FROM THE KODEA JOURNAL</span><h2>Ideas worth sharing.</h2></div><Link href="/blog" className="text-button">More insights <ArrowUpRight size={17}/></Link></Reveal><Reveal className="blog-grid">{posts.slice(0, 3).map(item => <BlogCard item={item} key={item.id}/>)}</Reveal></section></>;
}
function CodeIcon() { return <ServiceIcon name="Code" size={12}/>; }
